# Generated by Django 2.1.7 on 2019-03-27 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('documento', models.CharField(max_length=30)),
                ('correo', models.EmailField(max_length=254)),
                ('celular', models.CharField(max_length=10)),
                ('telefono', models.CharField(max_length=16)),
                ('direccion', models.CharField(max_length=70)),
                ('departamento', models.CharField(max_length=30)),
                ('ciudad', models.CharField(max_length=30)),
                ('fecha_nacimiento', models.DateField(max_length=30)),
                ('genero', models.CharField(max_length=30)),
                ('estado_civil', models.CharField(max_length=30)),
                ('ocupacion', models.CharField(max_length=30)),
            ],
        ),
    ]
