# Generated by Django 2.1.7 on 2019-03-27 19:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_compras_puntos'),
    ]

    operations = [
        migrations.AddField(
            model_name='compras',
            name='fecha_compra',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='fecha_notificacion',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='puntos',
            name='fecha_puntos',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
