# Generated by Django 2.1.7 on 2019-03-27 20:09

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_auto_20190327_1958'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=90)),
                ('tipo', models.CharField(max_length=90)),
                ('valor', models.CharField(max_length=999)),
                ('fecha_carrito', models.DateTimeField(default=datetime.date.today)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Lista_Favorito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=90)),
                ('tipo', models.CharField(max_length=90)),
                ('fecha_lista', models.DateTimeField(default=datetime.date.today)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.Usuario')),
            ],
        ),
        migrations.AlterField(
            model_name='compras',
            name='fecha_compra',
            field=models.DateTimeField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='fecha_notificacion',
            field=models.DateTimeField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='puntos',
            name='fecha_puntos',
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
