# Generated by Django 2.1.7 on 2019-03-27 20:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0005_auto_20190327_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrito',
            name='fecha_carrito',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='compras',
            name='fecha_compra',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='lista_favorito',
            name='fecha_lista',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='fecha_notificacion',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='puntos',
            name='fecha_puntos',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
