# Generated by Django 2.1.7 on 2019-03-28 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aliados', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aliado',
            name='imagen',
            field=models.ImageField(upload_to='static/img'),
        ),
    ]
