# Generated by Django 2.1.7 on 2019-03-27 20:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vuelo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desde', models.CharField(max_length=30)),
                ('hasta', models.CharField(max_length=30)),
                ('cuendo_viaja', models.ImageField(upload_to='photos')),
                ('cuando_vuelve', models.CharField(max_length=999)),
                ('numero_adultos', models.IntegerField(choices=[(1, '1'), (2, '2'), (1, '1'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], default=1)),
                ('numero_ninos', models.IntegerField(choices=[(1, '1'), (2, '2'), (1, '1'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], default=1)),
                ('tipo_cabina', models.CharField(choices=[('cualquiera', 'cualquiera'), ('economica', 'economica'), ('ejecutiva', 'ejecutiva'), ('primera_clase', 'primera clase')], default=1, max_length=40)),
                ('aerolinea', models.CharField(max_length=30)),
                ('hora_salida', models.TimeField(blank=True)),
                ('hora_regreso', models.TimeField(blank=True)),
                ('fecha_vuelo', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
