# Generated by Django 2.1.7 on 2019-03-27 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viajes', '0003_actividad_auto_hotel_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='numero_adultos',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], default=1),
        ),
        migrations.AlterField(
            model_name='plan',
            name='numero_habitaciones',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], default=1),
        ),
        migrations.AlterField(
            model_name='plan',
            name='numero_ninos',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], default=1),
        ),
    ]
