# Generated by Django 2.1.7 on 2019-03-28 15:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viajes', '0004_auto_20190327_2115'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotel',
            old_name='cuendo_sales',
            new_name='cuando_sales',
        ),
        migrations.RenameField(
            model_name='vuelo',
            old_name='cuendo_viaja',
            new_name='cuando_viaja',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='cuendo_viaja',
        ),
        migrations.AddField(
            model_name='plan',
            name='cuando_viaja',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='plan',
            name='cuando_vuelve',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
