# Generated by Django 2.1.7 on 2019-03-28 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viajes', '0005_auto_20190328_1512'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vuelo',
            name='aerolinea',
        ),
        migrations.RemoveField(
            model_name='vuelo',
            name='hora_regreso',
        ),
        migrations.RemoveField(
            model_name='vuelo',
            name='hora_salida',
        ),
        migrations.RemoveField(
            model_name='vuelo',
            name='tipo_cabina',
        ),
    ]
