# Generated by Django 2.1.7 on 2019-03-27 20:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bono',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=30)),
                ('imagen', models.ImageField(upload_to='photos')),
                ('puntos', models.CharField(max_length=999)),
                ('fecha_bono', models.DateTimeField(default=datetime.date.today)),
            ],
        ),
    ]
