# Generated by Django 2.1.7 on 2019-03-27 20:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bono',
            name='fecha_bono',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
